name: cohort-manager

services:
  # CaaS Integration Service
  retrieve-mesh-file:
    container_name: retrieve-mesh-file
    image: cohort-manager-retrieve-mesh-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/RetrieveMeshFile/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [non-essential]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - MeshApiBaseUrl=${INTERNAL_MESH_MESSAGEEXCHANGE_URL}
      - BSSMailBox=X26ABC1
      - MeshPassword=${MESHPASSWORD}
      - MeshSharedKey=${MESHSHAREDKEY}
      - MeshKeyName=meshpfx.pfx
      - MeshKeyPassphrase=${MESHKEYPASSPHRASE}
      - ASPNETCORE_URLS=http://*:7059

  nems-mesh-retrieval:
    container_name: nems-mesh-retrieval
    image: cohort-manager-nems-mesh-retrieval
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: NemsSubscriptionService/NemsMeshRetrieval/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [nems]
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - nemsmeshfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - NemsMeshApiBaseUrl=${INTERNAL_MESH_MESSAGEEXCHANGE_URL}
      - NemsMeshMailBox=${NEMS_MESH_MAILBOX}
      - NemsMeshPassword=${NEMS_MESH_PASSWORD}
      - NemsMeshSharedKey=${NEMS_MESH_SHARED_KEY}
      - NemsMeshKeyName=nemsmeshpfx.pfx
      - NemsMeshKeyPassphrase=${NEMS_MESH_KEY_PASSPHRASE}
      - NemsMeshBypassServerCertificateValidation=true
      - NemsMeshInboundContainer=nems-updates
      - NemsMeshConfigContainer=nems-config
      - ASPNETCORE_URLS=http://*:7058

  process-nems-update:
    container_name: process-nems-update
    image: cohort-manager-process-nems-update
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: NemsSubscriptionService/ProcessNemsUpdate/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:9083
      - nemsmeshfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - NemsMessages=nems-updates
      - NemsPoisonContainer=nems-poison
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - RetrievePdsDemographicURL=${RETRIEVE_PDS_DEMOGRAPHIC_API_BASE_URL}RetrievePDSDemographic
      - ManageNemsSubscriptionUnsubscribeURL=${MANAGE_NEMS_SUBSCRIPTION_API_BASE_URL}Unsubscribe
      - ManageNemsSubscriptionSubscribeURL=${MANAGE_NEMS_SUBSCRIPTION_API_BASE_URL}Subscribe
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
      - ParticipantManagementTopic=participant-management-topic

  receive-caas-file:
    container_name: receive-caas-file
    image: cohort-manager-receive-caas-file
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: CaasIntegration/receiveCaasFile/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - caasfolder_STORAGE=${AZURITE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://*:7060
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService
      - DemographicURI=${DURABLE_DEMOGRAPHIC_FUNCTION_API_BASE_URL}DurableDemographicFunction_HttpStart
      - GetOrchestrationStatusURL=${DURABLE_DEMOGRAPHIC_FUNCTION_API_BASE_URL}GetOrchestrationStatus
      - AllowDeleteRecords=true
      - BatchSize=3500
      - maxNumberOfChecks=50
      - recordThresholdForBatching=3
      - batchDivisionFactor=5
      - ScreeningLkpDataServiceURL=${SCREENING_LKP_DATA_SERVICE_API_BASE_URL}ScreeningLkpDataService
      - inboundBlobName=inbound
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
      - fileExceptions=file-exceptions
      - ParticipantManagementTopic=participant-management-topic

  # Participant Management Service
  manage-participant:
    container_name: manage-participant
    image: cohort-manager-manage-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageParticipant/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ServiceBusConnectionString_internal=${SERVICE_BUS_CONNECTION_STRING}
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
      - CohortDistributionTopic=cohort-distribution-topic
      - ParticipantManagementTopic=participant-management-topic
      - ManageParticipantSubscription=manage-participant-sub
      - ParticipantManagementUrl=${PARTICIPANT_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ParticipantManagementDataService
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException

  manage-servicenow-participant:
    container_name: manage-servicenow-participant
    image: cohort-manager-manage-servicenow-participant
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/ManageServiceNowParticipant/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [service-now]
    environment:
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ManageServiceNowParticipantSubscription=manage-servicenow-participant-sub
      - ServiceBusConnectionString_internal=${SERVICE_BUS_CONNECTION_STRING}
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
      - RetrievePdsDemographicURL=${RETRIEVE_PDS_DEMOGRAPHIC_API_BASE_URL}RetrievePDSDemographic
      - SendServiceNowMessageURL=${SERVICENOW_MESSAGE_HANDLER_API_BASE_URL}send
      - ParticipantManagementURL=${PARTICIPANT_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ParticipantManagementDataService
      - ManageNemsSubscriptionSubscribeURL=${MANAGE_CAAS_SUBSCRIPTION_API_BASE_URL}Subscribe
      - CohortDistributionTopic=cohort-distribution-topic

  update-blocked-flag:
    container_name: update-blocked-flag
    image: cohort-manager-update-blocked-flag
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/UpdateBlockedFlag/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [non-essential]
    ports:
      - "7027:7027"
    environment:
      - ASPNETCORE_URLS=http://*:7027
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ParticipantManagementUrl=${PARTICIPANT_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ParticipantManagementDataService
      - ParticipantDemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService/
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - ManageNemsSubscriptionUnsubscribeURL=${MANAGE_CAAS_SUBSCRIPTION_API_BASE_URL}Unsubscribe
      - ManageNemsSubscriptionSubscribeURL=${MANAGE_CAAS_SUBSCRIPTION_API_BASE_URL}Subscribe
      - RetrievePdsDemographicURL=${RETRIEVE_PDS_DEMOGRAPHIC_API_BASE_URL}RetrievePDSDemographic

  delete-participant:
    container_name: delete-participant
    image: cohort-manager-delete-participant
    networks: [cohman-network]
    profiles: [non-essential]
    ports:
    - "7087:7087"
    build:
      context: ./src/Functions/
      dockerfile: ParticipantManagementServices/DeleteParticipant/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://*:7087
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - CohortDistributionDataServiceURL=${COHORT_DISTRIBUTION_DATA_SERVICE_API_BASE_URL}CohortDistributionDataService/
      - AcceptableLatencyThresholdMs=500


  # Screening Data Service
  create-exception:
    container_name: create-exception
    image: cohort-manager-create-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/CreateException/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=${EXCEPTION_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ExceptionManagementDataService/
      - GPPracticeDataServiceURL=${GP_PRACTICE_DATA_SERVICE_API_BASE_URL}GPPracticeDataService/

  update-exception:
    container_name: update-exception
    image: cohort-manager-update-exception
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ExceptionHandling/UpdateException/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [non-essential]
    environment:
      - ASPNETCORE_URLS=http://*:7070
      - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
      - ExceptionManagementDataServiceURL=${EXCEPTION_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ExceptionManagementDataService/

  get-validation-exceptions:
    container_name: get-validation-exceptions
    image: cohort-manager-get-validation-exceptions
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: screeningDataServices/GetValidationExceptions/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [ui]
    environment:
      - ASPNETCORE_URLS=http://*:7071
      - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService/
      - ExceptionManagementDataServiceURL=${EXCEPTION_MANAGEMENT_DATA_SERVICE_API_BASE_URL}ExceptionManagementDataService/
      - GPPracticeDataServiceURL=${GP_PRACTICE_DATA_SERVICE_API_BASE_URL}GPPracticeDataService/
      - AcceptableLatencyThresholdMs=500

  # Screening Validation Service
  static-validation:
    container_name: static-validation
    image: cohort-manager-static-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/StaticValidation/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://*:7074
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}

  lookup-validation:
    container_name: lookup-validation
    image: cohort-manager-lookup-validation
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ScreeningValidationService/LookupValidation/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://*:7075
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - BsSelectGpPracticeUrl=${REFERENCE_DATA_SERVICE_API_BASE_URL}BsSelectGpPractice
      - BsSelectOutCodeUrl=${REFERENCE_DATA_SERVICE_API_BASE_URL}BsSelectOutCode
      - CurrentPostingUrl=${REFERENCE_DATA_SERVICE_API_BASE_URL}CurrentPosting
      - ExcludedSMULookupUrl=${REFERENCE_DATA_SERVICE_API_BASE_URL}ExcludedSMU
      - BlobContainerName=rules
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}

  # Demographic Services
  retrieve-pds-demographic:
    container_name: retrieve-pds-demographic
    image: cohort-manager-retrieve-pds-demographic
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/RetrievePDSDemographic/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [service-now, nems]
    ports:
      - 8082:8082
    environment:
      - ASPNETCORE_URLS=http://*:8082
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - RetrievePdsParticipantURL=${NHS_PDS_FHIR_R4_BASE_URL}Patient
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService
      - Kid=RetrievePdsDemographic-DEV1
      - Audience=${NHS_INT_OAUTH_BASE_URL}token
      - AuthTokenURL=${NHS_INT_OAUTH_BASE_URL}token
      - LocalPrivateKeyFileName=RetrievePdsDemographic-DEV1.pem.key
      - ParticipantManagementTopic=participant-management-topic
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
      - ClientId=Get-private-key-from-NHS-dev-portal
      - UseFakePDSServices=true

  manage-nems-subscription:
      container_name: manage-nems-subscription
      image: cohort-manager-manage-nems-subscription
      networks: [cohman-network]
      profiles: [nems, service-now]
      build:
        context: ./src/Functions/
        dockerfile: DemographicServices/ManageNemsSubscription/Dockerfile
        args:
          BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
      environment:
        - ASPNETCORE_URLS=http://*:9081
        - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
        - ParticipantDemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService
        - RetrievePdsDemographicURL=${RETRIEVE_PDS_DEMOGRAPHIC_API_BASE_URL}RetrievePDSDemographic
        - NemsFhirEndpoint=${NHS_INT_SPINE_BASE_URL}STU3
        - NemsFromAsid=200000002527
        - NemsToAsid=200000002527
        - NemsOdsCode=T8T9T
        - NemsMeshMailboxId=${NEMS_MESH_MAILBOX_ID}
        - NemsLocalCertPath=./nhs_signed_client.pfx
        - NemsLocalCertPassword=${NEMS_CERT_PASSWORD}
        - NemsSubscriptionProfile=${NHS_FHIR_STRUCTURE_DEFINITION_BASE_URL}EMS-Subscription-1
        - NemsSubscriptionCriteria=${NHS_FHIR_ID_BASE_URL}nhs-number
        - NemsDefaultEventTypes0=pds-record-change-1
        - NemsBypassServerCertificateValidation=true
        - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
        - IsStubbed=true
      ports:
        - "9081:9081"

  manage-caas-subscription:
      container_name: manage-caas-subscription
      image: cohort-manager-manage-caas-subscription
      networks: [cohman-network]
      profiles: [nems]
      build:
        context: ./src/Functions/
        dockerfile: DemographicServices/ManageCaasSubscription/Dockerfile
        args:
          BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
      environment:
        - ASPNETCORE_URLS=http://*:9084
        - FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
        - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
        - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
        - CaasSubscriptionMeshApiBaseUrl=${MESH_API_BASE_URL:-https://localhost:8700/messageexchange}
        - MeshCaasPassword=password
        - MeshCaasSharedKey=TestKey
        - MeshCaasKeyName=
        - MeshCaasKeyPassword=
        - IsStubbed=false
        - CaasToMailbox=${CAAS_SUBSCRIBE_TO_MAILBOX:-CAAS_TO}
        - CaasFromMailbox=${CAAS_SUBSCRIBE_FROM_MAILBOX:-CAAS_FROM}
        - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
      ports:
        - "9084:9084"

  durable-demographic-function:
    container_name: durable-demographic-function
    image: cohort-manager-durable-demographic-function
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: DemographicServices/DemographicDurableFunction/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    environment:
      - ASPNETCORE_URLS=http://*:7079
      - WEBSITE_HOSTNAME=durable-demographic-function:7079
      - DtOsDatabaseConnectionString=${DTOS_DATABASE_CONNECTION_STRING}
      - DemographicDataServiceURL=${PARTICIPANT_DEMOGRAPHIC_DATA_SERVICE_API_BASE_URL}ParticipantDemographicDataService
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
      - AcceptableLatencyThresholdMs=500
      - MaxRetryCount=3

  # Service Now Integration Service
  servicenow-message-handler:
    container_name: servicenow-message-handler
    image: cohort-manager-servicenow-message-handler
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ServiceNowIntegration/ServiceNowMessageHandler/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [service-now]
    environment:
      - ASPNETCORE_URLS=http://*:9092
      - ServiceNowCasesDataServiceURL=${SERVICENOW_CASES_DATA_SERVICE_API_BASE_URL}ServiceNowCasesDataService
      - ServiceNowRefreshAccessTokenUrl=${WIREMOCK_BASE_URL}oauth_token.do
      - ServiceNowUpdateUrl=${WIREMOCK_BASE_URL}api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseUpdate
      - ServiceNowResolutionUrl=${WIREMOCK_BASE_URL}api/x_nhsd_intstation/nhs_integration/9c78f87c97912e10dd80f2df9153aff5/CohortCaseResolution
      - ServiceNowGrantType=refresh_token
      - ServiceNowClientId=MockClientId-123
      - ServiceNowClientSecret=MockClientSecret-123
      - ServiceNowRefreshToken=MockRefreshToken-123
      - ServiceNowParticipantManagementTopic=servicenow-participant-management-topic
      - ServiceBusConnectionString_client_internal=${SERVICE_BUS_CONNECTION_STRING}
    ports:
      - 9092:9092

  servicenow-cohort-lookup:
    container_name: servicenow-cohort-lookup
    image: cohort-manager-servicenow-cohort-lookup
    networks: [cohman-network]
    build:
      context: ./src/Functions/
      dockerfile: ServiceNowIntegration/ServiceNowCohortLookup/Dockerfile
      args:
        BASE_IMAGE: ${FUNCTION_BASE_IMAGE}
    profiles: [service-now]
    environment:
      - ASPNETCORE_URLS=http://*:7180
      - ExceptionFunctionURL=${CREATE_EXCEPTION_API_BASE_URL}CreateException
      - ServiceNowCasesDataServiceURL=${SERVICENOW_CASES_DATA_SERVICE_API_BASE_URL}ServiceNowCasesDataService
      - CohortDistributionDataServiceURL=${COHORT_DISTRIBUTION_DATA_SERVICE_API_BASE_URL}CohortDistributionDataService

  # UI
  web:
    container_name: web
    build:
      context: ./src/Web
      dockerfile: Dockerfile
    restart: always
    profiles: [ui]
    ports:
      - "3000:3000"
    networks: [cohman-network]

networks:
  cohman-network:
    external: true
